apiVersion: v1
kind: ConfigMap
metadata:
  name: django-dev-settings
data:
  ALLOWED_HOSTS: "*"
  UNRESTRICT_INTERFACES: '1'
  DJANGO_DEBUG: '1'

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: django-prod-settings
data:
  ALLOWED_HOSTS: "127.0.0.1,ctf.backyard-hg.xyz"
  UNRESTRICT_INTERFACES: '1'
  DJANGO_DEBUG: '0'
