apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: django
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django
        scrape: 'true'
    spec:
      containers:
      - name: django
        image: localhost:5001/ctf:latest
        envFrom:
        - configMapRef:
            name: django-prod-settings
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: minio-secret
        - secretRef:
            name: postgres-secret
        - secretRef:
            name: django-secret
        ports:
        - containerPort: 8000

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.28.0-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app.kubernetes.io/name: django
spec:
  selector:
    app.kubernetes.io/name: django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.28.0-standalone-strict/ingress-networking-v1.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
  labels:
    app.kubernetes.io/name: django-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: ctf.backyard-hg.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django
                port:
                  number: 80
