apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: localhost:5001/ctf:latest
        envFrom:
        - configMapRef:
            name: django-dev-settings
        - configMapRef:
            name: postgres-config
        - configMapRef:
            name: postgres-secret
        - configMapRef:
            name: django-secret
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
