# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.28.0-standalone-strict/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  labels:
    app.kubernetes.io/name: prometheus-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-server
    spec:
      containers:
        - name: prometheus-server
          image: prom/prometheus:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
              readOnly: true
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.28.0-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  labels:
    app.kubernetes.io/name: prometheus-server
spec:
  selector:
    app.kubernetes.io/name: prometheus-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP
