# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.28.0-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  labels:
    app.kubernetes.io/name: django
type: Opaque
stringData:
  DJANGO_SECRET_KEY: secret
